/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateModuleJniCpp.js
 */

#include "RNAudioStreamSpec.h"

namespace facebook {
namespace react {

static facebook::jsi::Value __hostFunction_NativeAudioStreamSpecJSI_startStream(
    facebook::jsi::Runtime& rt,
    TurboModule& turboModule,
    const facebook::jsi::Value* args,
    size_t count) {
  return static_cast<NativeAudioStreamSpecJSI*>(&turboModule)->startStream(
      rt,
      args[0].getString(rt),
      args[1].getObject(rt));
}

static facebook::jsi::Value __hostFunction_NativeAudioStreamSpecJSI_pauseStream(
    facebook::jsi::Runtime& rt,
    TurboModule& turboModule,
    const facebook::jsi::Value* args,
    size_t count) {
  return static_cast<NativeAudioStreamSpecJSI*>(&turboModule)->pauseStream(rt);
}

static facebook::jsi::Value __hostFunction_NativeAudioStreamSpecJSI_resumeStream(
    facebook::jsi::Runtime& rt,
    TurboModule& turboModule,
    const facebook::jsi::Value* args,
    size_t count) {
  return static_cast<NativeAudioStreamSpecJSI*>(&turboModule)->resumeStream(rt);
}

static facebook::jsi::Value __hostFunction_NativeAudioStreamSpecJSI_stopStream(
    facebook::jsi::Runtime& rt,
    TurboModule& turboModule,
    const facebook::jsi::Value* args,
    size_t count) {
  return static_cast<NativeAudioStreamSpecJSI*>(&turboModule)->stopStream(rt);
}

static facebook::jsi::Value __hostFunction_NativeAudioStreamSpecJSI_cancelStream(
    facebook::jsi::Runtime& rt,
    TurboModule& turboModule,
    const facebook::jsi::Value* args,
    size_t count) {
  return static_cast<NativeAudioStreamSpecJSI*>(&turboModule)->cancelStream(rt);
}

static facebook::jsi::Value __hostFunction_NativeAudioStreamSpecJSI_seekTo(
    facebook::jsi::Runtime& rt,
    TurboModule& turboModule,
    const facebook::jsi::Value* args,
    size_t count) {
  return static_cast<NativeAudioStreamSpecJSI*>(&turboModule)->seekTo(
      rt,
      args[0].getNumber());
}

static facebook::jsi::Value __hostFunction_NativeAudioStreamSpecJSI_setVolume(
    facebook::jsi::Runtime& rt,
    TurboModule& turboModule,
    const facebook::jsi::Value* args,
    size_t count) {
  return static_cast<NativeAudioStreamSpecJSI*>(&turboModule)->setVolume(
      rt,
      args[0].getNumber());
}

static facebook::jsi::Value __hostFunction_NativeAudioStreamSpecJSI_addListener(
    facebook::jsi::Runtime& rt,
    TurboModule& turboModule,
    const facebook::jsi::Value* args,
    size_t count) {
  static_cast<NativeAudioStreamSpecJSI*>(&turboModule)->addListener(
      rt,
      args[0].getString(rt));
  return facebook::jsi::Value::undefined();
}

static facebook::jsi::Value __hostFunction_NativeAudioStreamSpecJSI_removeListeners(
    facebook::jsi::Runtime& rt,
    TurboModule& turboModule,
    const facebook::jsi::Value* args,
    size_t count) {
  static_cast<NativeAudioStreamSpecJSI*>(&turboModule)->removeListeners(
      rt,
      args[0].getNumber());
  return facebook::jsi::Value::undefined();
}

NativeAudioStreamSpecJSI::NativeAudioStreamSpecJSI(
    std::shared_ptr<CallInvoker> jsInvoker)
    : TurboModule("RNAudioStream", jsInvoker) {
  methodMap_["startStream"] = MethodMetadata{2, __hostFunction_NativeAudioStreamSpecJSI_startStream};
  methodMap_["pauseStream"] = MethodMetadata{0, __hostFunction_NativeAudioStreamSpecJSI_pauseStream};
  methodMap_["resumeStream"] = MethodMetadata{0, __hostFunction_NativeAudioStreamSpecJSI_resumeStream};
  methodMap_["stopStream"] = MethodMetadata{0, __hostFunction_NativeAudioStreamSpecJSI_stopStream};
  methodMap_["cancelStream"] = MethodMetadata{0, __hostFunction_NativeAudioStreamSpecJSI_cancelStream};
  methodMap_["seekTo"] = MethodMetadata{1, __hostFunction_NativeAudioStreamSpecJSI_seekTo};
  methodMap_["setVolume"] = MethodMetadata{1, __hostFunction_NativeAudioStreamSpecJSI_setVolume};
  methodMap_["addListener"] = MethodMetadata{1, __hostFunction_NativeAudioStreamSpecJSI_addListener};
  methodMap_["removeListeners"] = MethodMetadata{1, __hostFunction_NativeAudioStreamSpecJSI_removeListeners};
}

} // namespace react
} // namespace facebook 